### ISSUE TITLE
why are all the `matrix_*_norm` under BLAS 1? 

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/stdBLAS#107]
@mhoemmen 
i see that all of `matrix_{frob, inf, one}_norm` are under blas1. Why? 
Shouldn't these be BLAS 2? Maybe i missed it in the spec document.

**Comment by fnrizzi** [comment]
I thought the BLAS level refers to the complexity, am I wrong? is that what you mean by reuse?

**Comment by mhoemmen** [comment]
The proposal was voted into the C++ Working Draft for C++@6 with the matrix norms in the BLAS 1 section of the proposal.
