### ISSUE TITLE
`matrix_frob_norm`: missing the overloads not accepting `init`

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/stdBLAS#108]
We are missing these:
```cpp
// TODO: Implement auto functions
#if 0
template<class in_matrix_t>
auto matrix_frob_norm(in_matrix_t A)
{
 
}

template<class ExecutionPolicy,
         class in_matrix_t>
auto matrix_frob_norm(ExecutionPolicy&& exec,
                      in_matrix_t A)
{

}
#endif
```

**Comment by fnrizzi** [comment]
implementation can be found here: https://github.com/NexGenAnalytics/stdBLAS/blob/blas1_kokkos_impl/include/experimental/__p1673_bits/blas1_matrix_frob_norm.hpp  lines 167-218

**Comment by mhoemmen** [comment]
@fnrizzi That's a lovely implementation; thank you! : - D  Were you thinking of making a PR?  There are only a couple things that would need fixing.

1. The rescaling algorithm is lovely, but it only makes sense for floating-point types.  (Frobenius norm of a matrix of integers makes sense, but rescaling would mess it up.) 
2. Our algorithm implementations can't generally assume that `Scalar x = 1.0`, `Scalar y(1.0)`, or even `Scalar z = 0.0` compile.  We can get zero by value initialization (`Scalar x{}`), but one is only a thing for built-in types.  (Most of our algorithms don't ask that types have a multiplicative identity.)

**Comment by fnrizzi** [comment]
> Were you thinking of making a PR? There are only a couple things that would need fixing.
> 1. The rescaling algorithm is lovely, but it only makes sense for floating-point types.  (Frobenius norm of a matrix of integers makes sense, but rescaling would mess it up.)
> 2. Our algorithm implementations can't generally assume that `Scalar x = 1.0`, `Scalar y(1.0)`, or even `Scalar z = 0.0` compile.  We can get zero by value initialization (`Scalar x{}`), but one is only a thing for built-in types.  (Most of our algorithms don't ask that types have a multiplicative identity.)

@mhoemmen  thanks for the feedback! I think there is some confusion here, the stuff you bring up is not something I added.
Let me explain: 
- the rescaling algorithm: I have not touched that, it was already there for the `matrix_frob_norm` :) 
- identity thing: yes i agree. The use of identity as you point out was already there ! You are referring to things like: `ssq = Scalar(1.0) + ssq * quotient * quotient;` right? that was already there!

For the `matrix_frob_norm` the only thing I added was the non-init overloads: so lines 167-218 in [this file](https://github.com/NexGenAnalytics/stdBLAS/blob/blas1_kokkos_impl/include/experimental/__p1673_bits/blas1_matrix_frob_norm.hpp).  Specifically, right now that addition is part of the branch i am working on for the kokkos stuff, but i can make a separate PR just for these overloads.

**Comment by mhoemmen** [comment]
@fnrizzi Sorry for the confusion!  I reworded #141 and added an issue https://github.com/kokkos/stdBLAS/issues/144 to address these points.
