### ISSUE TITLE
naming convention for `idx_abs_max` 

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/stdBLAS#109]
@mhoemmen 
It seems to me that the name `idx_abs_max` is inconsistent with how the other functions are named. 
We have: 
```
xASUM -> vector_abs_sum
xNRM2 -> vector_norm2
IxAMAX -> idx_abs_max
```
why not calling `vector_idx_abs_max`?

Also, along these lines, since all other names are pretty explicit, why not?
```cpp
vector_index_abs_max
```
Just two characters more :)

**Comment by mhoemmen** [comment]
That's a good question -- I think LEWG(I) wanted that changed, but I'll need to go back into the minutes, since it's not in the paper's changelog.

**Comment by mhoemmen** [comment]
Btw, I will argue for removal of `idx_abs_max`.  We do not need it, since we have `iota` , `cartesian_product`, and `reduce`.

**Comment by fnrizzi** [comment]
@mhoemmen why you think we don't need it?

**Comment by mhoemmen** [comment]
@fnrizzi It's very nearly a one-liner using ranges.  [Here is an example](https://godbolt.org/z/W15odaeoE) using `vector` instead of `mdspan`:
```c++
#include <algorithm>
#include <iostream>
#include <ranges>
#include <vector>

int main()
{
    std::vector<double> x{3.0, 4.0, 5.0, 6.0, -3.0, 7.0, -8.0, 1.0};

    auto theRange = std::views::iota(size_t(0), x.size()) | std::views::transform([=] (auto k) { return std::abs(x[k]); });
    auto iterOfMax = std::ranges::max_element(theRange);
    auto indexOfMax = std::ranges::distance(theRange.begin(), iterOfMax); // __int128 in GCC 12.1
    std::cout << "max element at: " << size_t(indexOfMax) << '\n';

    return 0;
}
```
For the `mdspan` version, just replace `x.size()` with `x.extent(0)`.

The neat thing about ranges is that in C++23, you'll be able to write a generic version for `mdspan` of any rank, by using `cartesian_product`.

**Comment by mhoemmen** [comment]
@fnrizzi Here's the parallel version https://godbolt.org/z/TGzGYEj4c

**Comment by fnrizzi** [comment]
@mhoemmen makes sense! 
I actually need to read more about ranges, I basically have zero experience with them. But that is the case with several of c++20 features. As you know probably sandia will upgrade to c++20 in 2030.

**Comment by mhoemmen** [comment]
@fnrizzi Sandia could use [ranges-v3](https://ericniebler.github.io/range-v3/) right now, but y'all like reimplementing things yourselves I guess ; - P .

**Comment by fnrizzi** [comment]
ah! 
That is min c++14, I think sandia *just* moved to 14 :)

**Comment by mhoemmen** [comment]
It's cool, I'm leaving this thing in there for now.

**Comment by fnrizzi** [comment]
ok, but i agree with you about removing!

**Comment by mhoemmen** [comment]
@fnrizzi Christian suggests leaving the BLAS 1 stuff in the proposal.

**Comment by mhoemmen** [comment]
Resolved in final version of the proposal (R13).
