### ISSUE TITLE
Spec has `{hermitian, symmetric}_matrix_{left,right}_product`  but in the code name is different

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/stdBLAS#111]
@mhoemmen 

in the spec http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1673r4.html#overview-of-contents
I see: 
```
xSYMM | symmetric_matrix_{left,right}_product
xHEMM | hermitian_matrix_{left,right}_product
```

but in the [code](https://github.com/kokkos/stdBLAS/blob/main/include/experimental/__p1673_bits/blas3_matrix_product.hpp), I only see: 
```cpp
symmetric_matrix_product
hermitian_matrix_product
```
It seems to me that the left/right scenario is handled inside even if the function has a generic name, so is the spec outdated?

**Comment by mhoemmen** [comment]
@amklinv-nnl I think so, but there was a [correctness issue](https://github.com/kokkos/stdBLAS/pull/87#discussion_r698924356).  We could just put `assert(false)` in those methods for now.
