### ISSUE TITLE
Spec has `triangular_matrix_matrix_{left,right}_solve`  but in the code name is different

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/stdBLAS#113]
Spec has `triangular_matrix_matrix_{left,right}_solve`  but in the code name is different: 
```cpp
triangular_matrix_matrix_solve
```
see https://github.com/kokkos/stdBLAS/blob/main/include/experimental/__p1673_bits/blas3_triangular_matrix_matrix_solve.hpp

**Comment by mhoemmen** [comment]
This should be fixed by PR #87.  Any remaining `assert(false)` is a separate issue, #116.
