### ISSUE TITLE
properly handling `accessor`, for example `scaled` in customizations

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/stdBLAS#122]
I need to revisit the kokkos-kernels impl of some functions, because I forgot to handle properly the accessor. 
When converting mdspan to view, this does not account for the accessor, e.g. `linalg::scaled`. 
So we need to account for accessors via the coefficients. Similarly to how the matrix_vector product is done. 

We currently have only a few kk implementations so this fix should be quick.

**Comment by fnrizzi** [comment]
@mhoemmen 
related to this, one clarification about please. 
Let's take the `add` function. This corresponds to `xAXPY`. 

Potentially, one can do:
```cpp
add(x, y, z)
add(scaled(2., x), y, z)
add(scaled(2., x), scale(4., y), z)
// ...
add(conjugated(x), scale(4., y), z) // assume x,y,z complex
// ... 
// etc 
```
So we end up with a lot of combinations because of the accessor things. 
In my mind, all these should be valid calls and work. Am I right?

**Comment by mhoemmen** [comment]
@fnrizzi wrote:
> In my mind, I see all these as valid calls that should work. Am I right?

If the corresponding C++ code implementing the algorithm "naively" would compile, then those are valid calls.  That sounds like a tautology but it's not.  For example, C++ doesn't let you mix arithmetic with `complex<float>` and `double`, but it does let you mix arithmetic with `float` and `double`.

With that caveat, yes, those calls should work in general.  You should always be able to apply any combination of `conjugated` and `scaled` to any input view, as long as the equivalent "naive" C++ code would work.

**Comment by fnrizzi** [comment]
@mhoemmen thanks! so that aligns with what I was thinking. I will work towards that. 

The second part of the "question": are there any other accessors one should keep in mind?

**Comment by mhoemmen** [comment]
> ... are there any other accessors one should keep in mind?

If you don't know the accessor type, then you certainly will need a custom `Kokkos::View` accessor that wraps the user's generic accessor.  A generic accessor can do pretty much anything; P0009 imposes few requirements.  As we saw with the `conjugated` / `scaled` bug, implementations can't ignore the nested accessor ; - ) .

If I were doing this work, I would start with a `Kokkos::View` that can wrap the user's generic accessor.  I would then specialize for specific accessor types like those used by `conjugated` and `scaled`.

**Comment by fnrizzi** [comment]
I totally agree on the specializations, in fact I have been working along those lines. All my questions above were meant to actually clarify and verify that you/we want to support all possible behaviors before jumping into it and spending time on it :) 
Since this is pretty delicate in my view. This accessor thing is not a 1 min fix :) 

Concrete scenario (maybe much down the road): I am using stdBLAS, and I want some custom behavior, like you say, so I define my custom accessor. Also, I use the Kokkos impl of stdblas and want to be able to run things on the host and device. 
The kokkos impl of stdBLAS does support arbitrary accessors. 
In such case, the accessor itself has to be defined so that Kokkos can wrap it behind the scenes and run it on the device. 
So, if I understand correctly, this means that my custom accessor has to have things like `KOKKOS_INLINE_FUNCTON` etc. right? Otherwise, it would not work. At least not in all cases. 
That also means that how I implement my custom accessor must be dependent also on the backend that i want to use as implementation. Am I right?

**Comment by fnrizzi** [comment]
ok, so I looked inside mdspan, and noticed that the default accessor does infact have a macro to make it for host and device. 
```cpp
  MDSPAN_FORCE_INLINE_FUNCTION
  constexpr reference access(pointer p, size_t i) const noexcept {
    return p[i];
  }
```
So I kind of answered my own doubt I guess.  
But, in the stdBLAS, both `conjugated` and `scaled` accessors are not marked for device/host. So that is what confused me a bit. 
And leads me to the following question: since stdBLAS uses mdspan, eventually we want all the blas functions to work on device too right? so the fact that now the `conjugated` and `scaled` accessors are just for host it is just temporary thing. correct?

**Comment by fnrizzi** [comment]
@mhoemmen @crtrott 

First question: granted that we want `scaled` and `conjugated` to work. 
But do we want to support in the kokkos impl totally arbitrary accessors ? 

If so, I was trying today to find a solution for this "arbitrary accessor" thing, but I am not sure what I have makes sense. 

Here is what I have:
```cpp
void add(x, y, z) // x,y,z are mdspans
{
  auto x_view = Impl::mdspan_to_view(x); // converting to view drops all accessor information
  auto y_view = Impl::mdspan_to_view(y); // converting to view drops all accessor information
  auto z_view = Impl::mdspan_to_view(z); // converting to view drops all accessor information

  const auto x_acc = x.accessor();
  const auto y_acc = y.accessor();
  const auto x_mapper = x.mapping();
  const auto y_mapper = y.mapping();
  Kokkos::parallel_for(x_view.extent(0),
		       KOKKOS_LAMBDA (const std::size_t i) {
			 z_view(i) = x_acc.access(x_view.data(), x_mapper(i)) + 
                                     y_acc.access(y_view.data(), y_mapper(i));
		       });
}
``` 
If converting to Kokkos views drops all knowledge of the original accessors, I don't see another way to carry on the accessors. Is there one? 
@mhoemmen you talked above about: "custom Kokkos::View accessor that wraps the user's generic accessor." what did you mean exactly with that? 

thanks

**Comment by mhoemmen** [comment]
@fnrizzi wrote:
> in the stdBLAS, both conjugated and scaled accessors are not marked for device/host. that is what confused me a bit.

Device/host markings are not Standard C++, but we could consider that in our implementation as a nonstandard extension.  (Our implementation started as a reference implementation.  It's become a bit more than that now.)  However, we should only mark those accessors as device/host, if the underlying nested accessor is device/host.

> you talked above about: "custom Kokkos::View accessor that wraps the user's generic accessor." what did you mean exactly with that?

The user might define their own accessor type that we don't know about.  That's what I mean by "generic accessor."

"Custom `Kokkos::View` accessor" means a ViewMapping, the thing that implements `Kokkos::View::operator()` by returning a reference.  This is the Kokkos equivalent(ish) to `mdspan`'s accessor policy.  You could define a custom ViewMapping by specializing on the second template parameter of `ViewMapping`.  This could be a way to turn an `mdspan` with arbitrary custom accessor type, into a `Kokkos::View`, without losing the user's custom accessor behavior.

In my view, this is way too much work.  If you see an accessor type that's not some combination of `default_accessor`, `accessor_conjugate`, and/or `accessor_scaled`, then just fall back to the naive sequential implementation of the BLAS operation.

**Comment by fnrizzi** [comment]
The ViewMapping explanation makes sense. I thought you had something else in mind for carrying over the accessors from mdspan to view. 

> In my view, this is way too much work. If you see an accessor type that's not some combination of `default_accessor`, `accessor_conjugate`, and/or `accessor_scaled`, then you can just fall back to the naive sequential implementation of the BLAS operation.

That is answer I was looking for. Makes sense to me. All my inquiring was meant to cover "all bases" so now that you say that, I am on the same page.

**Comment by mhoemmen** [comment]
It looks like this issue is resolved.  Please feel free to reopen if not.  Thanks!
