### ISSUE TITLE
Error in CI from mdspan

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/stdBLAS#124]
@crtrott @mhoemmen 
I am seeing this: https://github.com/kokkos/stdBLAS/runs/4274887773?check_suite_focus=true

```
Run make
-- Detected support for C++20 standard
-- -- Using "-fconcepts" to enable concepts support
-- Could NOT find BLAS (missing: BLAS_LIBRARIES) 
-- Build include directory: /__w/stdBLAS/stdBLAS/stdblas-build/include/experimental
-- Configuring done
-- Generating done
-- Build files have been written to: /__w/stdBLAS/stdBLAS/stdblas-build
Scanning dependencies of target trmm
[  2%] Building CXX object tests/CMakeFiles/trmm.dir/trmm.cpp.o
In file included from /__w/stdBLAS/stdBLAS/mdspan-install/include/experimental/__p0009_bits/extents.hpp:46,
                 from /__w/stdBLAS/stdBLAS/stdblas-src/include/experimental/__p1673_bits/maybe_static_size.hpp:46,
                 from /__w/stdBLAS/stdBLAS/stdblas-src/include/experimental/linalg:48,
                 from /__w/stdBLAS/stdBLAS/stdblas-src/tests/trmm.cpp:1:
/__w/stdBLAS/stdBLAS/mdspan-install/include/experimental/__p0009_bits/layout_left.hpp:136:9: error: 'layout_stride' was not declared in this scope; did you mean 'layout_type'?
  136 |         _MDSPAN_TRAIT(is_same, typename OtherMapping::layout_type, layout_stride) &&
      |         ^~~~~~~~~~~~~
make[2]: *** [tests/CMakeFiles/trmm.dir/build.make:63: tests/CMakeFiles/trmm.dir/trmm.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:129: tests/CMakeFiles/trmm.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Error: Process completed with exit code 2.
```

this seems new... any thoughts? 
thanks

**Comment by mhoemmen** [comment]
`layout_left.hpp` might need a forward declaration of `layout_stride` around line 54.  I'll make a PR.

**Comment by mhoemmen** [comment]
`layout_right.hpp` already has forward declarations of both `layout_left` and `layout_stride`, so the one change implemented by the PR might be enough.

**Comment by dalg24** [comment]
I don't follow how the `layout_left.hpp` header is being included from the error message above but I feel like including private headers from the `mdspan` implementation is asking for trouble
https://github.com/kokkos/stdBLAS/blob/b1be6719a37603c023b34b7f129a0eeed0172147/include/experimental/__p1673_bits/maybe_static_size.hpp#L46-L48

**Comment by mhoemmen** [comment]
@dalg24 wrote:
> but I feel like including private headers from the mdspan implementation is asking for trouble

Oof, ya, I don't like that either.  That looks like an implementation detail of the "BLAS layouts" that got copy-pasted from mdspan.  I'll file an issue in stdBLAS to address this.
