### ISSUE TITLE
Implementation includes private headers from the mdspan implementation

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/stdBLAS#126]
The implementation includes private (implementation detail) headers from the `mdspan` implementation.  [Here is an example.](https://github.com/kokkos/stdBLAS/blob/b1be6719a37603c023b34b7f129a0eeed0172147/include/experimental/__p1673_bits/maybe_static_size.hpp#L46-L48).  This came up [in discussion here](https://github.com/kokkos/stdBLAS/issues/124#issuecomment-974869228).

**Comment by crtrott** [comment]
We should not include private headers. Note: mdspan is currently explicitly NOT designed to have self contained headers, the all have a pragma once.

**Comment by fnrizzi** [comment]
https://github.com/kokkos/stdBLAS/pull/128
