### ISSUE TITLE
P1673: `matrix_frob_norm`: incomplete spec 

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/stdBLAS#143]
it seems to me that [this](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1673r6.html#frobenius-norm-with-specified-result-type) is missing two things:
1. it does not say how to use `init`
2. shouldn't it have: `Preconditions: abs(A[0,0]) shall be convertible to T.`?

**Comment by mhoemmen** [comment]
Thanks for pointing this out!  I've expanded the description of `matrix_frob_norm` in P1673R7 (to be submitted tonight) to include these details.
