### ISSUE TITLE
P1673: Fix arithmetic with scaled_scalar and other proxy reference types

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/stdBLAS#145]
1. For proxy reference types like `scaled_scalar`, there are both overloaded operators and conversion operators.  This causes ambiguity for cases like `scaled_scalar(a)*scaled_scalar(b)`.
2. `scaled_scalar` and the other proxy reference types need to implement arithmetic operators, if its underlying type implements them.  This means something like the following, for instance:
```
template<class T>
class scaled_scalar {
   // ...
   template<class T2>
   auto operator / (T2 val) requires(std::decltype<T>() / std::decltype<T2>()) {
     return (scaled*value)/val;
   }
   // ...
};
```
3. Evaluate whether this approach works also for `std::complex`.

These changes relate to the proposal and the implementation.  We'll test the changes in the implementation, then apply them to the proposal.

**Comment by youyu3** [comment]
Another issue as a result of this is that: `conj_if_needed` as defined in `conjugate_if_needed.hpp` doesn't work for things like `conj_if_needed(scaled(alpha,x))`, since `decltype(value)` doesn't return a complex data type.

**Comment by mhoemmen** [comment]
@youyu3 Thanks for pointing this out!  It's reasonable for us to consider fixing `conj_if_needed` for `scaled_scalar` and `conjugated_scalar`.

**Comment by mhoemmen** [comment]
I haven't had time to work on this for P1673R7.  I'd rather do it right with an implementation first then try to jam it into the proposal, but I do plan to work on this (and would welcome other people taking this up as well!).

**Comment by youyu3** [comment]
Yep, makes sense to have an implementation first.

**Comment by mhoemmen** [comment]
Here's a start: https://godbolt.org/z/crj51Kxre

**Comment by mhoemmen** [comment]
Here's a bit more progress: https://godbolt.org/z/nMjs5b7cd

Fun fact: `std::atomic_ref` only has specializations with arithmetic operators for floating-point, integer, and pointer types, not for `std::complex<T>`.  Fixing it required arithmetic operator overloads for `atomic_ref<complex<T>>` and `complex<T>`.  That feels out of scope for P1673.  Please see the comment above the following macro definition:
```c++
// Uncomment the line below to enable the Reference overloads,
// and operator+ overloads for (atomic_ref<complex<T>>, const complex<T>&)
// and (const complex<T>&, atomic_ref<complex<T>>).
#define P1673_CONJUGATED_SCALAR_ARITHMETIC_OPERATORS_REFERENCE_OVERLOADS 1
```

**Comment by mhoemmen** [comment]
I now have full tests for a custom complex number type, `FakeComplex`: https://godbolt.org/z/f7z47xWqv

**Comment by mhoemmen** [comment]
Tests now include a `scaled_scalar` implementation: https://godbolt.org/z/58a9xj9hK

**Comment by mhoemmen** [comment]
@youyu3 Thanks for all the new tests!  I figured out a fix for this particular issue.  Please see lines 598-606 at [this Compiler Explorer link](https://godbolt.org/z/389jrfd1q).
```c++
// Avoid an ambiguous overload
template<class SF1, class Ref1, class SF2, class Ref2>
auto operator+ (const scaled_scalar<SF1, Ref1>& ss1,
    const scaled_scalar<SF2, Ref2>& ss2)
{
    using value_type_1 = typename scaled_scalar<SF1, Ref1>::value_type;
    using value_type_2 = typename scaled_scalar<SF2, Ref2>::value_type;
    return value_type_1(ss1) + value_type_2(ss2);
}
```
I don't think I like this general approach, though.  It means that for every binary arithmetic operator, the number of required overloads would grow exponentially with the number of proxy references in our proposal.  We already need eight:

1. `(conjugated_scalar, T)`
2. `(T, conjugated_scalar)`
3. `(scaled_scalar, T)`
4. `(T, scaled_scalar)`
5. `(conjugated_scalar<V1,R1>, conjugated_scalar<V2,R2>)`
6. `(scaled_scalar<V1,R1>, scaled_scalar<V2,R2>)`
7. `(conjugated_scalar<V1,R1>, scaled_scalar<V2,R2>)`
8. `(scaled_scalar<V1,R1>, conjugated_scalar<V2,R2>)`

Suppose that we wrote an exposition-only customization point `proxy_to_value`, that invokes conversion-to-value for our proxy reference types, and is the identity for everything else.

```c++
template<class T>
auto proxy_to_value(T t) { return t; }

template<class V, class R>
auto proxy_to_value(conjugated_scalar<V, R> t) {
  // maybe we should call this type alias "value_type" as well
  return typename conjugated_scalar<V, R>::conjugate_result_t(t);
}

template<class V, class R>
auto proxy_to_value(scaled_scalar<V, R> t) {
  return typename scaled_scalar<V, R>::value_type(t);
}
```

WG21 has been expressing a preference lately for the "hidden friend" style of operators.  We could use this, plus `proxy_to_value`, to write one fully generic `operator+` (for example) for each proxy reference type.  For example:

```c++
template<class ScalingFactor, class Reference>
class scaled_scalar { // exposition only
private:
  ScalingFactor scaling_factor;
  Reference value;

public:
  using element_type = decltype(scaling_factor * value);
  using value_type = std::remove_cv_t<element_type>;

  scaled_scalar(const ScalingFactor& s, Reference v) : scaling_factor(s), value(v) {}

  operator value_type() const { // changed from element_type
      return scaling_factor * value;
  }

  template<class SF, class Ref, class Rhs>
  friend auto operator+(scaled_scalar<SF, Ref> ss, Rhs rhs) {
    return proxy_to_value(ss) + proxy_to_value(rhs);
  }
};
```

What do you think of this approach?

**Comment by mhoemmen** [comment]
It's not _quite_ like that syntax, btw -- I'm working on it.

**Comment by mhoemmen** [comment]
Update: I have an implementation fix, as well as a wording fix (in PR https://github.com/ORNL/cpp-proposals-pub/pull/258 ).  PR for implementation fix will come soon.

**Comment by mhoemmen** [comment]
It turns out we didn't need proxy reference types.  The accessors just return a "reference" that's a value, like `std::vector<bool>::operator[] const` does.
