### ISSUE TITLE
P1673: `triangular_matrix_vector_product`: checking the wrong condition for diagonal

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/stdBLAS#148]
In the impl we currently have:

```cpp
constexpr bool explicitDiagonal = std::is_same_v<DiagonalStorage, explicit_diagonal_t>;
```

However, in the spec we have:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/18708772/158145640-b6eb8e64-5e0a-4d91-bd3e-b85753f5d624.png">

so I would say that `explicit_diagonal_t` should not be used to check the condition but it should be based on `implicit_unit_diagonal_t` as follows: 
```cpp
  constexpr bool implicitUnitDiagonal = std::is_same_v<DiagonalStorage, implicit_unit_diagonal_t >;
  // or 
  constexpr bool explicitlyAccessDiagonal = !std::is_same_v<DiagonalStorage, implicit_unit_diagonal_t >;
```

**Comment by mhoemmen** [comment]
**[linalg.algs.reqs]** says that "`DiagonalStorage` is either `implicit_unit_diagonal_t` or `explicit_diagonal_t`."  Thus, it is undefined behavior to give any other type for this tag parameter, so the current implementation is equivalent to your proposal.  That being said, I wouldn't mind if the implementation changed.  It's just that you don't have to worry about it.

Thanks for taking a look at this, btw!
