### ISSUE TITLE
P1673: spec: in-place triangular mat vec is missing exec-policy-accepting overload

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/stdBLAS#150]
seems like in the spec [here](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1673r6.html#in-place-triangular-matrix-vector-product-linalgalgsblas2trmvin-place) the `triangular_matrix_vector_product` that does in-place operation only shows this api:
```cpp
template<class in_matrix_t,
         class Triangle,
         class DiagonalStorage,
         class inout_vector_t>
void triangular_matrix_vector_product(
  in_matrix_t A,
  Triangle t,
  DiagonalStorage d,
  inout_vector_t y);
```

so is missing the overload accepting execution policy. If there is a reason for omitting it, it is not explicitly stated.

**Comment by mhoemmen** [comment]
Excellent catch! : - )  R2 added "in-place overloads of `triangular_matrix_matrix_{left,right}_solve`, `triangular_matrix_{left,right}_product`, and `triangular_matrix_vector_solve`."  We must have missed the matrix-vector product.

We'll also need to change the following explanatory text:
> For triangular solve and triangular multiply, in-place behavior is essential for computing matrix factorizations in place, without requiring extra storage proportional to the input matrix’s dimensions. However, in-place functions cannot be parallelized for arbitrary execution policies. Thus, we have both not-in-place and in-place overloads, and only the not-in-place overloads take an optional `ExecutionPolicy&&`.

**Comment by mhoemmen** [comment]
This will be fixed in P1673R7, which I'm submitting tonight.  Thanks for pointing this out!
