### ISSUE TITLE
No alpha overloads for {symmetric,hermitian}_matrix_rank_1_update 

### ISSUE THREAD

**Issue by mzuzek** [kokkos/stdBLAS#156]
@mhoemmen @fnrizzi 

It seems that `alpha` overloads of `symmetric_matrix_rank_1_update()` and `hermitian_matrix_rank_1_update()` are missing in [the current `main`](https://github.com/kokkos/stdBLAS/blob/60ecb0053c6a60437920f69a17de712e82d37e1c/include/experimental/__p1673_bits/blas2_matrix_rank_1_update.hpp#L250-L418).

> **Note:** alpha overloads were introduced in R2 and no-alpha overloads were removed in R4 (see [revision history](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1673r6.html#revision-history)) because of template ambiguity issue (see #134, #136, #138 and #139).

**Comment by MikolajZuzek** [comment]
Does this duplicate #138 ?
