### ISSUE TITLE
P1673R6 typo

### ISSUE THREAD

**Issue by MikolajZuzek** [kokkos/stdBLAS#158]
@mhoemmen @fnrizzi 

Looks like there is `A[j,k]` instead of `A[j,i]` in _Remarks_ for [16.9.3.6.4. Rank-1 update of a Hermitian matrix](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1673r6.html#rank-1-update-of-a-hermitian-matrix-linalgalgsblas2rank1her) :

![typo](https://user-images.githubusercontent.com/29018159/162272008-2effb0e0-ca2c-4c08-be68-75b438d5a355.png)

**Comment by mhoemmen** [comment]
Thanks for pointing this out!  I'll make another pass through P1673 before the new submission deadline.

**Comment by mhoemmen** [comment]
I'm submitting P1673R7 tonight with minor fixes, including this one.  Thanks for pointing this out! : - )
