### ISSUE TITLE
gtest requirement

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/stdBLAS#2]
stdBLAS currently requires Google Test (gtest) in order to build the tests.  The configure fails otherwise.

We could resolve this issue as follows:

1. Snapshot gtest into the repo
2. Provide instructions how to build gtest separately

**Comment by upsj** [comment]
I just stumbled across this repo - we had the same question in Ginkgo, and basically went for a third option (similar to 1.): If it was not found, fetch gtest using CMake's `FetchContent` and build it as part of the normal build process. If you are interested, I can provide a PR for this.

**Comment by mhoemmen** [comment]
@upsj That would be excellent; thank you!!! : - D  What would happen if `FetchContent` can't access the internet?  (I'm OK with it failing, if the user didn't provide their own gtest implementation.)  Also, does gtest change very often?

**Comment by upsj** [comment]
> What would happen if FetchContent can't access the internet?

Yes, the fetch step would fail then, but only if it hasn't been fetched in the same build path. Example output:
```
[1/9] Creating directories for 'mdspan-populate'
[1/9] Performing download step (git clone) for 'mdspan-populate'
Cloning into 'mdspan-src'...
fatal: unable to access 'https://github.com/kokkos/mdspan.git/': Could not resolve host: github.com
Cloning into 'mdspan-src'...
fatal: unable to access 'https://github.com/kokkos/mdspan.git/': Could not resolve host: github.com
Cloning into 'mdspan-src'...
fatal: unable to access 'https://github.com/kokkos/mdspan.git/': Could not resolve host: github.com
-- Had to git clone more than once:
          3 times.
CMake Error at mdspan-subbuild/mdspan-populate-prefix/tmp/mdspan-populate-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/kokkos/mdspan.git'


FAILED: mdspan-populate-prefix/src/mdspan-populate-stamp/mdspan-populate-download
cd /mnt/c/Users/tobi/stdBLAS/build/_deps && /usr/local/bin/cmake -P /mnt/c/Users/tobi/stdBLAS/build/_deps/mdspan-subbuild/mdspan-populate-prefix/tmp/mdspan-populate-gitclone.cmake && /usr/local/bin/cmake -E touch /mnt/c/Users/tobi/stdBLAS/build/_deps/mdspan-subbuild/mdspan-populate-prefix/src/mdspan-populate-stamp/mdspan-populate-download
ninja: build stopped: subcommand failed.

CMake Error at /usr/local/share/cmake-3.18/Modules/FetchContent.cmake:989 (message):
  Build step for mdspan failed: 1
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/FetchContent.cmake:1105:EVAL:2 (__FetchContent_directPopulate)
  /usr/local/share/cmake-3.18/Modules/FetchContent.cmake:1105 (cmake_language)
  CMakeLists.txt:78 (FetchContent_Populate)
```
>  Also, does gtest change very often?

Depends on what you mean by change. There are regular commits and releases to the repo, but we have been fine with using a pinned commit hash/version and only changing it every so often if we need new features. The test setup itself seems to be pretty stable over the recent versions.

**Comment by mhoemmen** [comment]
We've long since resolved this.
