### ISSUE TITLE
BLAS 1: Add vector_abs_sum functions

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/stdBLAS#20]

**Comment by amklinv-nnl** [comment]
I don't think we need to capture the loop unrolling, but we should probably grab the extra tests and close the issue.

**Comment by mhoemmen** [comment]
@amklinv-nnl Per our discussion today, we definitely don't need to implement the reference BLAS' hand-unrolled loops.  We've implemented the function (it's [here](https://github.com/kokkos/stdBLAS/blob/main/include/experimental/__p1673_bits/blas1_vector_abs_sum.hpp)) and just need to add the tests.  Thanks!
