### ISSUE TITLE
P1673: typos in definition of upper/lower triangle

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/stdBLAS#214]
in the proposal: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1673r6.html#triangle-tags-linalgtagstriangle

<img width="865" alt="image" src="https://user-images.githubusercontent.com/18708772/170064282-58882e2d-d38f-4167-b4bc-aa2a6de7d0e8.png">

I think that the definitions of upper and lower triangle are flipped: 
- "The upper triangle of a matrix `A` is the set of all elements of `A` accessed by `A[i,j]` with `i >= j`" 
   This should be: "...  accessed by `A[i,j]` with `i <= j`" 
- "The lower triangle of a matrix `A` is the set of all elements of `A` accessed by `A[i,j]` with `i <= j`" 
   This should be: "...  accessed by `A[i,j]` with `i >= j`"

**Comment by fnrizzi** [comment]
@mhoemmen i can make a PR to fix proposal

**Comment by mhoemmen** [comment]
@fnrizzi I've incorporated your fixes in PR https://github.com/ORNL/cpp-proposals-pub/pull/258 for Revision 9.  That PR also fixes the analogous issue with `layout_blas_packed`.  Thanks!
