### ISSUE TITLE
Infinite recursion on missing implementation

### ISSUE THREAD

**Issue by mzuzek** [kokkos/stdBLAS#218]
@mhoemmen @crtrott @fnrizzi 

If an algorithm is called with execution policy that has identical mapping (i.e. `execpolicy_mapper` returns same type as it gets) - like `kokkos_exec<ExecSpace>` - but implementation (or that particular overload) is missing, the dispatcher enters infinite recursion. It results in SEGFAULT crash in `Debug` builds or hangs in `Release` builds (e.g. see [the hanging tests cancelled after 25m](https://github.com/kokkos/stdBLAS/runs/6571220999?check_suite_focus=true)).

This happens because `is_custom_<ALG>_avail` checks mistake _the dispatcher routine_ for requested custom implementation (as - with id policy mapping - their function signatures are identical).

**Comment by MikolajZuzek** [comment]
One possible solution would be to have `is_custom_<ALG>_avail` checks detect that the dispatcher routine is detected as the custom function like:
```cpp
std::is_same_v< std::experimental::linalg::triangular_matrix_left_product, // dispatcher
                    /* ADL namespace :: */ triangular_matrix_left_product >      // detected custom implementation
```
For example:
```cpp
template <class Exec, class A_t, class Tr_t, class DiagSt_t, class C_t>
struct is_custom_triang_mat_left_product_with_update_avail<
  Exec, A_t, Tr_t, DiagSt_t, C_t,
  std::enable_if_t<
    std::is_void_v<decltype(
	       triangular_matrix_left_product
	       (std::declval<Exec>(),
		std::declval<A_t>(),
		std::declval<Tr_t>(),
		std::declval<DiagSt_t>(),
		std::declval<C_t>()))>

    // check if custom implementation is different than the dispatcher to prevent inf recursion
    && !std::is_same_v< 
      decltype(
	       std::experimental::linalg::triangular_matrix_left_product
	       (std::declval<Exec>(),
            std::declval<A_t>(),
            std::declval<Tr_t>(),
            std::declval<DiagSt_t>(),
            std::declval<C_t>())),
      decltype(
	       triangular_matrix_left_product
	       (std::declval<Exec>(),
            std::declval<A_t>(),
            std::declval<Tr_t>(),
            std::declval<DiagSt_t>(),
            std::declval<C_t>()))>

    && !linalg::impl::is_inline_exec_v<Exec>
    >
  >
  : std::true_type{};
```

**Comment by fnrizzi** [comment]
@crtrott just to clarify that Mikolaj and I talked about this, and decided to open the issue but even if you find it useful, we will *not* address it right away because we first want to complete the Kokkos implementations to satisfy the contract.

**Comment by youyu3** [comment]
@mhoemmen I don't quite understand the scenario that had infinite recursion yet, but I have a case with identical mapping, and the implementation is available, which works without this fix, and doesn't work with this fix.

**Comment by mhoemmen** [comment]
@youyu3 Please feel free to reopen if this is still broken; thanks!

**Comment by mzuzek** [comment]
@mhoemmen @youyu3 @fnrizzi

I've created PR #249 to revert PR #222.

As pointed out by @srinivasyadav18 on #248 (probably first mentioned by @youyu3 [above](https://github.com/kokkos/stdBLAS/issues/218#issuecomment-1175553168)) the implementation is completely incorrect, because that `decltype` formulation proposed [above](https://github.com/kokkos/stdBLAS/issues/218#issuecomment-1137094702) puts function's return type into comparison instead of its full signature. And even that wouldn't work, since compared functions do have same the same type/signature - they just lay in different namespaces.

I can't see any good implementation of the concept based on comparing functions yet, because even if there's a good way to compare functors, TPL implementations can have arbitrary template parameters which don't seem to be derivable from function parameter types available in `is_custom_<ALG>_avail`...

**Comment by mhoemmen** [comment]
@crtrott I do not like that the reference implementation is trying to ADL-find some customization points with the same names.  

The proposal is still in flight.  LEWG asked us to change function names in R12.  When we make those changes here, we will break whatever code depends on those names.

The Right Way is to separate stdBLAS's public interface from its implementation.  Any customization points should have DIFFERENT NAMES.  Users should not have to worry about compiler errors because the call to `matrix_vector_product` is ambiguous between `std::linalg::matrix_vector_product` and `my_funny_namespace::matrix_vector_product`.

**Comment by mhoemmen** [comment]
I'm reopening this issue, because we really need to discuss this design.

**Comment by youyu3** [comment]
Note this is still broken since #249 isn't merged yet.
