### ISSUE TITLE
Question regarding conj_if_needed

### ISSUE THREAD

**Issue by stigrs** [kokkos/stdBLAS#246]
At line 87 in conjugated_if_needed.hpp, `conj_if_needed` is implemented as:
```
auto conj_if_needed = [](const auto& t)
{
  using T = std::remove_const_t<decltype(t)>;
  return conj_if_needed_impl(t, has_conj<T>{});
};
```
Is this code missing `template <class T>` or `inline`? As the code is now, it will be defined multiple times.

**Comment by mhoemmen** [comment]
@stigrs Thanks for pointing this out!  I've pushed a commit to PR #245 that fixes this.
