### ISSUE TITLE
Finish mdarray overloads of all functions that need them

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/stdBLAS#29]

**Comment by amklinv-nnl** [comment]
Please close this issue or elaborate further on which ones need mdarray overloads

**Comment by mhoemmen** [comment]
We decided not to include the `basic_mdarray` overloads in R2 of P1673: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1673r2.pdf  Thanks for asking! : - )
