### ISSUE TITLE
matrix_vector_product: fix y(i) initialization on lines 63 & 127

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/stdBLAS#32]
Lines 63 and 127 of [`blas2_matrix_vector_product.hpp`](https://github.com/kokkos/stdBLAS/blob/e41346193c1a36c67ade9f110dc7d4d5d372d9fc/include/experimental/__p1673_bits/blas2_matrix_vector_product.hpp#L63) use `0.0` to initialize `y(i)`.  They should use `typename out_vector_t::value_type{}` instead.

**Comment by amklinv-nnl** [comment]
I'm on it.

**Comment by amklinv-nnl** [comment]
I did the same thing in the BLAS3 matrix product function. If that is incorrect, feel free to cherry-pick my commit over.

**Comment by mhoemmen** [comment]
PR https://github.com/kokkos/stdBLAS/pull/34 has a fix -- thanks!
