### ISSUE TITLE
Add ExecutionPolicy overloads of in-place triangular_matrix_* functions (see list)

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/stdBLAS#45]
Add `ExecutionPolicy` overloads of the in-place versions of `triangular_matrix_vector_solve`, `triangular_matrix_left_product`, `triangular_matrix_right_product`, `triangular_matrix_matrix_left_solve`, and `triangular_matrix_matrix_right_solve`.

**Comment by amklinv-nnl** [comment]
Some of these functions don't even exist yet
- [ ] triangular_matrix_vector_solve
- [ ] triangular_matrix_left_product
- [ ] triangular_matrix_right_product
- [ ] triangular_matrix_matrix_left_solve
- [ ] triangular_matrix_matrix_right_solve

**Comment by mhoemmen** [comment]
Ah, I see, `triangular_matrix_matrix_left_solve` and `triangular_matrix_matrix_right_solve` are replacements for a function that took sided-ness as an argument:

https://github.com/kokkos/stdBLAS/blob/08bc0b513affa40ce21633c24053e4d52f789baa/include/experimental/__p1673_bits/blas3_triangular_matrix_matrix_solve.hpp#L267

**Comment by mhoemmen** [comment]
We already have implementations of those functions; they just have the wrong names and live in an anonymous namespace.

**Comment by amklinv-nnl** [comment]
Do we want to move them out of the anonymous namespace or update the docs?

**Comment by mhoemmen** [comment]
@amklinv-nnl wrote:
> Do we want to move them out of the anonymous namespace or update the docs?

The former, please.  The names in P1673 are the names we want, so we just need to fix the implementation.  Thanks! : - )
