### ISSUE TITLE
P1673R3: vector_norm2 is missing one-parameter 'auto' overload (taking only vector)

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/stdBLAS#63]
Issues prefixed with "P1673R3" refer to the proposal itself, not necessarily the reference implementation.

**Comment by amklinv-nnl** [comment]
Is this what you're looking for, or did I misunderstand?

![image](https://user-images.githubusercontent.com/64440832/122127232-e0b1c280-ce00-11eb-859b-fbb5b7235734.png)

**Comment by mhoemmen** [comment]
@amklinv-nnl Yup that is it, thanks! : - D

**Comment by amklinv-nnl** [comment]
The true fix was inside you all along! Feel free to close the issue.

**Comment by mhoemmen** [comment]
@amklinv-nnl w00000 thanks! : - )
