### ISSUE TITLE
Make the implementation enforce basic_mdspan-ness

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/stdBLAS#67]
P1673's template parameter names like `in_vector_t` come with constraints (e.g., must be a rank-1 `basic_mdspan`).  The implementation needs to enforce that, by only overloading for `basic_mdspan` types instead of just templating on e.g., `in_vector_t`.  
For examples, see `vector_norm2` and `matrix_inf_norm`.

**Comment by amklinv-nnl** [comment]
On it.

**Comment by amklinv-nnl** [comment]
What do we want to do about

```
template<class in_vector_t,
         class out_vector_t>
void swap_rank_1(in_vector_t x,
                 out_vector_t y)
```
I assume only certain type combinations make sense.

**Comment by mhoemmen** [comment]
`swap_rank_1` doesn't exist any more.  `swap_elements` takes `inout_object_{1,2}_t` and further constrains the two types to have the same rank.  We might need to go function by function to include all the constraints (that means "will not participate in overload resolution unless," not `static_assert` (Mandates)).

**Comment by amklinv-nnl** [comment]
My bad; they're totally in an anonymous namespace.

**Comment by mhoemmen** [comment]
We probably should still use the right names there, though -- `inout_vector_{1,2}_t` would be more appropriate for the rank 1 case.

**Comment by amklinv-nnl** [comment]
This comment is to track the progress on various files.

- [x] blas1_dot
- [ ] blas1_givens
- [ ] blas1_linalg_add
- [ ] blas1_linalg_copy
- [ ] blas1_linalg_swap
- [ ] blas1_matrix_frob_norm
- [x] blas1_matrix_inf_norm
- [ ] blas1_matrix_one_norm
- [x] blas1_scale
- [x] blas1_vector_abs_sum
- [x] blas1_vector_idx_abs_max
- [x] blas1_vector_norm2
- [x] blas1_vector_sum_of_squares
- [ ] blas2_matrix_rank_1_update
- [ ] blas2_matrix_rank_2_update
- [ ] blas2_matrix_vector_product
- [ ] blas2_matrix_vector_solve
- [ ] blas3_matrix_product
- [ ] blas3_matrix_rank2k_update
- [ ] blas3_triangular_matrix_solve
