### ISSUE TITLE
P1673R3: Change ptrdiff_t to extents<>::size_type

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/stdBLAS#74]
P0009 now uses `size_t` instead of `ptrdiff_t`.  P1673R3 uses `ptrdiff_t` in a few places.  Change all of them to `extents<>::size_type`, so that we're just coupled to P0009 instead of needing to update this ever again.

**Comment by amklinv-nnl** [comment]
This should be resolved by #68.

**Comment by mhoemmen** [comment]
https://github.com/ORNL/cpp-proposals-pub/pull/142 will fix this.
