### ISSUE TITLE
P1673: BLAS comparison table says sum_of_squares; should be vector_sum_of_squares to match normative wording

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/stdBLAS#98]
@mhoemmen 

in http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1673r4.html#overview-of-contents

there is: 
```
N/A | sum_of_squares
```
should this be `vector_sum_of_squares`? at least in the source code this is the name

**Comment by mhoemmen** [comment]
Should be fixed by https://github.com/ORNL/cpp-proposals-pub/pull/186 .

**Comment by mhoemmen** [comment]
Fixed in R6; thanks for reporting! : - )
